### ISSUE TITLE
Color tweaks for visiblity

### ISSUE THREAD

**Issue by jacksonludwig** [404cn/nano-theme.el#1]
Hello and thanks for maintaining this package.

I noticed that the selection/highlight color is the same as org-mode source code blocks. Of course, this makes it hard to see what you're highlighting in source blocks, and perhaps it would be better for either the highlight or the source block face to be made lighter/darker.

Another option is removing the source code block background altogether, which some other themes do and personally I think is nice, but I'm not sure if that's a popular opinion.

What do you think?

**Comment by lakkiy** [comment]
Thanks for your feedback!

I got this problem too when I try to start to use nano-emacs with my own config, and I haven't see what org-mode source code blocks looks like, I just split it from nano-emacs right now, it still some work to do like this.

I think removing the source code block background altogether is not a good idea, because you can see where the code is fast at a glance.

Maybe add some other effect will be better, like background color to blocks header or bold, underline etc.

Also any pr and idea are welcome.

**Comment by lakkiy** [comment]
I delete background color of source code block and add background to block begin and end.

See https://github.com/404cn/nano-theme.el/commit/77d2b2dbc444dc59e81a1b221eea8b6d008a3a89
